import { TaskModel } from '@/models/TaskModel';
import { dbConnect } from '@/utils/mongoose';
import { serializeToJSON } from '@/utils/serializeToJSON';
import Head from 'next/head';

export default function HomePage({ tasks }) {
  console.log('frontend');

  console.log(tasks);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta
          name='description'
          content='Generated by create next app'
        />
        <meta
          name='viewport'
          content='width=device-width, initial-scale=1'
        />
        <link
          rel='icon'
          href='/favicon.ico'
        />
      </Head>
      <h1>Hello World</h1>
    </>
  );
}

export async function getServerSideProps(context) {
  console.log('backend');

  dbConnect();
  const tasks = serializeToJSON(await TaskModel.find());

  return {
    props: {
      tasks
    }
  };
}
