GET http://localhost:3000/api/tasks HTTP/1.1
###

GET http://localhost:3000/api/tasks/ HTTP/1.1

###

POST http://localhost:3000/api/tasks HTTP/1.1
Content-Type: application/json

{
  "title": "my tasks",
  "description": "this is a task"
}

###

PUT http://localhost:3000/api/tasks/646ff7b045acfe466a1ad04a HTTP/1.1
Content-Type: application/json

{
  "title": "my tasks20",
  "description": "this is a task"
} 


###

DELETE http://localhost:3000/api/tasks/646feb9e31ff4dd5e1b1b813 HTTP/1.1